//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增日程 的本地化字符串。
        /// </summary>
        internal static string addcalendar {
            get {
                return ResourceManager.GetString("addcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全天日程 的本地化字符串。
        /// </summary>
        internal static string alldayevent {
            get {
                return ResourceManager.GetString("alldayevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/Javascripts/Plugins/xgcalendar_lang_zh_CN.js 的本地化字符串。
        /// </summary>
        internal static string calendar_langpack_url {
            get {
                return ResourceManager.GetString("calendar_langpack_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭窗口 的本地化字符串。
        /// </summary>
        internal static string closetitle {
            get {
                return ResourceManager.GetString("closetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待建中... 的本地化字符串。
        /// </summary>
        internal static string comingsoon {
            get {
                return ResourceManager.GetString("comingsoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string confirmformtitle {
            get {
                return ResourceManager.GetString("confirmformtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/Javascripts/Plugins/datepicker_lang_zh_CN.js 的本地化字符串。
        /// </summary>
        internal static string datepicker_langpack_url {
            get {
                return ResourceManager.GetString("datepicker_langpack_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-M-d 的本地化字符串。
        /// </summary>
        internal static string datestring {
            get {
                return ResourceManager.GetString("datestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常抱歉，无法加载您的活动，请稍后再试 的本地化字符串。
        /// </summary>
        internal static string defaulterrormsg {
            get {
                return ResourceManager.GetString("defaulterrormsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要删除该日程? 的本地化字符串。
        /// </summary>
        internal static string deleteconfirm {
            get {
                return ResourceManager.GetString("deleteconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消该日程 的本地化字符串。
        /// </summary>
        internal static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理日程 的本地化字符串。
        /// </summary>
        internal static string editcalendar {
            get {
                return ResourceManager.GetString("editcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文 的本地化字符串。
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击切换到日视图 的本地化字符串。
        /// </summary>
        internal static string goto_dayview_title {
            get {
                return ResourceManager.GetString("goto_dayview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击切换到月视图 的本地化字符串。
        /// </summary>
        internal static string goto_monthview_title {
            get {
                return ResourceManager.GetString("goto_monthview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击切换到周视图 的本地化字符串。
        /// </summary>
        internal static string goto_weekview_title {
            get {
                return ResourceManager.GetString("goto_weekview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载数据... 的本地化字符串。
        /// </summary>
        internal static string loaddatamsg {
            get {
                return ResourceManager.GetString("loaddatamsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点 的本地化字符串。
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建日程 的本地化字符串。
        /// </summary>
        internal static string new_event {
            get {
                return ResourceManager.GetString("new_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击新建日程 的本地化字符串。
        /// </summary>
        internal static string new_event_title {
            get {
                return ResourceManager.GetString("new_event_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个 的本地化字符串。
        /// </summary>
        internal static string next_title {
            get {
                return ResourceManager.GetString("next_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的时间格式 的本地化字符串。
        /// </summary>
        internal static string notvoliddatetimeformat {
            get {
                return ResourceManager.GetString("notvoliddatetimeformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}无效 的本地化字符串。
        /// </summary>
        internal static string parameterinvalid {
            get {
                return ResourceManager.GetString("parameterinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个 的本地化字符串。
        /// </summary>
        internal static string prev_title {
            get {
                return ResourceManager.GetString("prev_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理请求... 的本地化字符串。
        /// </summary>
        internal static string processdatamsg {
            get {
                return ResourceManager.GetString("processdatamsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string refresh_title {
            get {
                return ResourceManager.GetString("refresh_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string savetitle {
            get {
                return ResourceManager.GetString("savetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间不能大于结束时间 的本地化字符串。
        /// </summary>
        internal static string starttimegreatthanendtime {
            get {
                return ResourceManager.GetString("starttimegreatthanendtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功! 的本地化字符串。
        /// </summary>
        internal static string successmsg {
            get {
                return ResourceManager.GetString("successmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的日程 的本地化字符串。
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到 的本地化字符串。
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击返回当前日程 的本地化字符串。
        /// </summary>
        internal static string today_title {
            get {
                return ResourceManager.GetString("today_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看日程 的本地化字符串。
        /// </summary>
        internal static string viewcalendar {
            get {
                return ResourceManager.GetString("viewcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        internal static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
    }
}
